from natural_selection_methods import NaturalSelectionMethods


POPULATION_SIZE = 30
NUMBER_OF_GENERATIONS = 40
NUMBER_OF_GENES = 9
BITS_PER_GENE = 4
INDIVIDUAL_LENGTH = NUMBER_OF_GENES * BITS_PER_GENE
NATURAL_SELECTION_METHOD = NaturalSelectionMethods.TOURNAMENT
